name: scout_co
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  age_calculator: ^1.0.0
  bloc: ^8.1.4
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_colorpicker: ^1.1.0
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  meta: ^1.12.0
  pdf: ^3.11.1
  printing: ^5.13.2
  shared_preferences: ^2.3.2
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true
  class_name: I10n
  main_locale: en
  arb_dir: lib/core/localization/l10n
  output_dir: lib/core/localization/generated   